packages:
  - 'packages/*'
  - 'apps/*'
  - '!apps/vimax/**'
  - 'modules/*'
allowBuilds:
  '@google/genai': true
  '@prisma/client': false
  '@prisma/engines': false
  aws-sdk: false
  canvas: true
  core-js: true
  core-js-pure: true
  es5-ext: false
  esbuild: true
  husky: false
  prisma: false
  protobufjs: true
  puppeteer: true
  sharp: true
  unrs-resolver: false
  workerd: true
