packages:
  - 'packages/*'
  - 'apps/*'
  - '!apps/vimax/**'
  - 'modules/*'
allowBuilds:
  '@google/genai': true
  canvas: true
  core-js: true
  core-js-pure: true
  esbuild: true
  protobufjs: true
  puppeteer: true
  sharp: true
  unrs-resolver: set this to true or false
  workerd: true
